def get():
  return [
    {
      'region': 'Sudoeste - Paraná',
      'text': ' É, mano, o top é que ali, né, mano, num raio ali tem boleiras de gente, né, é bastante circulação de pessoa e gente que mora e circulação de pessoa, né, mano, porque é... cidade turística...',
      'file-name': './audio/bruno-pr.ogg',
      'transcribed-text': '',
      'runtime': 0,
      'text-size': 0,
      'transcribed-text-size': 0,
      'wrong-words': [],
      'number-wrong-words': 0,
      'error-percentage': 0,
      'lang': 'pt-br'
    },
    {
      'region': 'Oeste - Santa Catarina',
      'text': 'Claro, ano que vem fizemo alguma coisinha, vamo ta com a casa nova também. Ai fizemo, uns petisco, beleza?',
      'file-name': './audio/carlos-sc.ogg',
      'transcribed-text': '',
      'runtime': 0,
      'text-size': 0,
      'transcribed-text-size': 0,
      'wrong-words': [],
      'number-wrong-words': 0,
      'error-percentage': 0,
      'lang': 'pt-br'
    },
    {
      'region': 'Sul - Bahia',
      'text': ' Demorou, mano. Veja aí, veja aí. Vem jogar sim, mano. Não está difícil, ta ligado? É a gurizada da casa, que está jogando, mano. Cinquentão, pra ganhar... pra ganhar... milzão, né? Então, o investimento, né? Válido.',
      'file-name': './audio/gabriel-ba.ogg',
      'transcribed-text': '',
      'runtime': 0,
      'text-size': 0,
      'transcribed-text-size': 0,
      'wrong-words': [],
      'number-wrong-words': 0,
      'error-percentage': 0,
      'lang': 'pt-br'
    },
    {
      'region': 'Teresina - Piauí',
      'text': ' Mano, a gente teve que chegar aqui no, na nordus antes, saca, que tinha mesa reservada, eu pensava que era 8 que tinha que chegar nós, ai a Andressa falou que é as 7, se arrume cola pra cá mano, pega um Uber aí.',
      'file-name': './audio/leonardo-pi.ogg',
      'transcribed-text': '',
      'runtime': 0,
      'text-size': 0,
      'transcribed-text-size': 0,
      'wrong-words': [],
      'number-wrong-words': 0,
      'error-percentage': 0,
      'lang': 'pt-br'
    },
    {
      'region': 'Interior - São Paulo',
      'text': 'Então foi isso né, o Leo botou lá tipo, eu vou botar isso aqui, isso aqui, isso aqui, o que precisa depois de gente compra, e o caslu levou um whisky a mais pra garantir né e daí o resto a gente teve que comprar mesmo, eu levei uns 3kg de carne, o mineiro levou um porco, o caslu mandou lá um, uma medalhão lá, e foi nessa, entendeu? Mas suave biridi, tudo nosso pai',
      'file-name': './audio/leonardo-sp.ogg',
      'transcribed-text': '',
      'runtime': 0,
      'text-size': 0,
      'transcribed-text-size': 0,
      'wrong-words': [],
      'number-wrong-words': 0,
      'error-percentage': 0,
      'lang': 'pt-br'
    },
    {
      'region': 'Capital - São Paulo',
      'text': ' Mano, bagulho é que eu cheguei em casa, ai o Thiago me deu um salve e nós piou, mas não piou no after errado, tá ligado? Tipo, tinha dois after eu nem sabia, ele tinha, ele tava com o nome na lista em um e eu tava com o nome na lista em outro',
      'file-name': './audio/marcos-sp.ogg',
      'transcribed-text': '',
      'runtime': 0,
      'text-size': 0,
      'transcribed-text-size': 0,
      'wrong-words': [],
      'number-wrong-words': 0,
      'error-percentage': 0,
      'lang': 'pt-br'
    },
    {
      'region': 'Rio de Janeiro',
      'text': 'Ah, ô Léo Brandão, 2h50 da tarde, né, meu amigo? Tu vai ficar mandando essas mensagens? Pelo amor de Deus, mano. Geral boladão no trabalho, tu tendo que...... pô, tem que ficar lendo essas merda que tu escreve?',
      'file-name': './audio/matheus-rj.ogg',
      'transcribed-text': '',
      'runtime': 0,
      'text-size': 0,
      'transcribed-text-size': 0,
      'wrong-words': [],
      'number-wrong-words': 0,
      'error-percentage': 0,
      'lang': 'pt-br'
    },
    {
      'region': 'Santos - São Paulo',
      'text': 'E aí mano vai ter aquele bondezinho Centro Efapi. Dos atleta. Quem vai fazer o auxílio transporte atleta?',
      'file-name': './audio/maycon-sa.ogg',
      'transcribed-text': '',
      'runtime': 0,
      'text-size': 0,
      'transcribed-text-size': 0,
      'wrong-words': [],
      'number-wrong-words': 0,
      'error-percentage': 0,
      'lang': 'pt-br'
    },
    {
      'region': 'Minas Gerais',
      'text': 'Fala biridi, bom dia. Uai, mano. O que cê qué que eu falo? Eu juro que saca ali. Mas aqui é o que eu falo que é daí.',
      'file-name': './audio/paulo-ms.ogg',
      'transcribed-text': '',
      'runtime': 0,
      'text-size': 0,
      'transcribed-text-size': 0,
      'wrong-words': [],
      'number-wrong-words': 0,
      'error-percentage': 0,
      'lang': 'pt-br'
    },
    {
      'region': 'Santa Catarina',
      'text': '"Ma vai com o Conte pia, já não me convidou no último dia que foram, então convide ele né mano agora ta me convidando por que ele falou que não tava afim de ir.',
      'file-name': './audio/vitor-sc.ogg',
      'transcribed-text': '',
      'runtime': 0,
      'text-size': 0,
      'transcribed-text-size': 0,
      'wrong-words': [],
      'number-wrong-words': 0,
      'error-percentage': 0,
      'lang': 'pt-br'
    },
  ]